---
- name: validate states on EOS devices
  hosts: ATD_LAB
  gather_facts: false

  # Requires AVD > 4.4.2
  tasks:
    - name: validate states on EOS devices
      ansible.builtin.import_role:
         name: arista.avd.eos_validate_state
      vars:
        use_anta: true
        save_catalog: true
